import type { Metadata } from "next";
import "./globals.css";
import { Raleway } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";

const raleway = Raleway({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-raleway",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} antialiased`}>{children}</body>
      <Toaster />
    </html>
  );
}
